# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-17 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20171016_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealitem',
            name='order',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Order'),
        ),
    ]
